apiVersion: v1
kind: Pod
metadata:
  name: my-multicontainer-pod
spec:
  containers:
  - name: web-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: sidecar-container
    image: busybox:latest
    command: ['sh', '-c', 'echo Hello from the sidecar container!']
